/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function normalizeJson(payloadJson: string): string
export declare function deterministicHash(payloadJson: string): string
export interface NormalizeAndHashResult {
  normalizedJson: string
  deterministicHash: string
}
export interface ProcessExportPayloadResult {
  normalizedJson: string
  decodedJson: string
  decodedValueHash: string
  decodedSchemaJson: string
  decodedSchemaHash: string
  protobufStructBytes: Buffer
}
export interface BuildSpanProtoBytesInput {
  traceId: string
  spanId: string
  parentSpanId: string
  name: string
  packageName: string
  instrumentationName: string
  submoduleName: string
  packageType: number
  environment?: string
  kind: number
  inputSchemaJson: string
  outputSchemaJson: string
  inputSchemaHash: string
  outputSchemaHash: string
  inputValueHash: string
  outputValueHash: string
  statusCode: number
  statusMessage: string
  isPreAppStart: boolean
  isRootSpan: boolean
  timestampSeconds: number
  timestampNanos: number
  durationSeconds: number
  durationNanos: number
  metadataJson?: string
  inputValueJson?: string
  outputValueJson?: string
  inputValueProtoStructBytes?: Buffer
  outputValueProtoStructBytes?: Buffer
}
export declare function normalizeAndHash(payloadJson: string): NormalizeAndHashResult
export declare function objectToProtobufStructBytes(payloadJson: string): Buffer
export declare function objectToProtobufStructFieldCount(payloadJson: string): number
export declare function processExportPayload(payloadJson: string, schemaMergesJson?: string | undefined | null): ProcessExportPayloadResult
export declare function buildSpanProtoBytes(input: BuildSpanProtoBytesInput): Buffer
export declare function buildExportSpansRequestBytes(observableServiceId: string, environment: string, sdkVersion: string, sdkInstanceId: string, spans: Array<Buffer>): Buffer
